en_url : "data/small_vocab_en"
fr_url : "data/small_vocab_fr"
type_model : "Lstm_Embd" # use "Rnn" or "Rnn_Embd" or "Lstm" or "Lstm_Embd"
learning_rate : 0.004
number_sample : 137861
batch_size : 512
epochs : 1
validation_split : 0.2
type_device : "CPU"

# Structural Models

length_vector_word: 2
n_neurons_embedding: 256
n_neurons_rnn: 256
n_neurons_lstm: 256
n_neurons_timedistributed: 1024

#config.yaml
image: "dog.jpg"
classesf: "yolov3.txt"
weights: "yolov3.weights"
config: "yolov3.cfg"
scale: 0.00392
classes: None