en_url : "data/small_vocab_en"
fr_url : "data/small_vocab_fr"
type_model : "Rnn_Embd"
learning_rate : 0.004
number_sample : 137861
batch_size : 512
epochs : 10
validation_split : 0.2
type_device : "GPU"



# structre model
