name: CI Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image and Run tests
        run: |
          docker build --file Dockerfile --tag ammarmoulla/machine_translate:v1
          docker run ammarmoulla/machine_translate:v1
  
  # push:
  #   name: Push To Docker
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
        
  #     - name: build and push
  #       run: |
  #         docker build . --file Dockerfile --tag ammarmoulla/machine_translate:v1
  #         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #         docker push ammarmoulla/machine_translate:v1